[versions]
#App deps
lombok = "1.18.34"
slf4j = "1.7.36"
jetbrains-annotation = "25.0.0"

#Test Modules
junit-jupiter = "5.12.0-RC2"



[libraries]
#App deps
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotation" }

#Test Modules
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
